version: '3.8'

services:
  isna-website:
    build: .
    container_name: isna-web
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./logs:/var/log/httpd
      - ./logs/php-fpm:/var/log/php-fpm
    networks:
      - isna-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  isna-network:
    driver: bridge
